name: "Projectmanagement workflow"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - checkout@v3
      - run: echo "Building Projectmanagement..."
      - run: make build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - checkout@v3
      - run: echo "Testing Projectmanagement..."
      - run: make test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - checkout@v3
      - run: echo "Deploying Projectmanagement..."
      - run: make deploy
